steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/notes-app:$SHORT_SHA', 
      '-t', 'gcr.io/$PROJECT_ID/notes-app:latest', 
      '.'
    ]

  # 2. Push the container image with the short SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/notes-app:$SHORT_SHA']

  # 3. Push the container image with the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/notes-app:latest']

# Top-level field
logs_bucket: 'gs://log-bucket1112'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/notes-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/notes-app:latest'
